title: Hoon Lab at Pharmacy, SKKU
email: nyj990613@gmail.com
author: Hoon Lab
description: > # this means to ignore newlines until "baseurl:"

# DO NOT CHANGE THE LINE OF THIS FILE without editing .circleci/circle_urls.sh
baseurl: "" # the subpath of your site, e.g. /blog

# This is mostly for testing
url: "https://hoonbiolab.github.io" # the base hostname & protocol for your site



# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"
logo_width: 20
logo_pixels: 20
color: grey # primary color for header, buttons

# Build settings
markdown: kramdown
accentColor: "grey" # purple, green, etc.
themeColor: "grey" # purple, green, blue, orange, purple, grey
fixedNav: true # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
