remote_theme: daattali/beautiful-jekyll
plugins:
  - github-pages
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-include-cache
#  - jekyll-redirect-from
#  - jekyll-mentions
#  - jekyll-twitter-plugin

title: Hoon Lab at Pharmacy, SKKU
author: Hoon Kim


navbar-links:
  Team: "team"
  Research: "research"
  Publications: "publications"
  Contact: "contact"

#avatar: "/assets/img/KakaoTalk_Photo_2019-04-01-23-00-12.jpeg"

social-network-links:
  email: "wisekh6@gmail.com"
  #facebook: wisekh6
  github: hoonbiolab
  twitter: wisekh6
  #linkedin: "pub/dean-attali/8/946/143"
  #stackoverflow: "users/3943160/daattali"
  #calendly: "attalitech/meeting"
  #youtube: "c/daattali?sub_confirmation=1"
  #patreon: DeanAttali

#share-links-active:
#  twitter: true
#  facebook: true
#  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "Cancer, Tumor evolution, Bioinformatics, Extrachromosomal DNA, Machine learning"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "Korea/Seoul"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

#disqus: "deanattali-site"
#google_analytics: "UA-59820529-1"
#fb_app_id: "536330676521989"

#url-pretty: "❤ Support"
#url-canonical: https://github.com/sponsors/daattali

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: false
      comments: false
      social-share: false
      show-share: false
      show-subscribe: false
      support_promo_box: false
      after-content: [share-section.html, purpleads.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: false
      comments: false
      social-share: false
      show-share: false
      show-subscribe: false
      support_promo_box: false
      after-content: [share-section.html, purpleads.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
